import type { Config } from 'tailwindcss';

const config: Config = {
  content: ['./src/**/*.{ts,tsx}'],
  darkMode: ['class', '[data-theme="dark"]'],
  theme: {
    extend: {
      colors: {
        // Raw scales from tokens.css — oklch-derived, hue ~258 neutral
        gray: {
          25:  '#fbfcfd',
          50:  '#f6f8fb',
          100: '#eef1f6',
          200: '#e3e8ef',
          300: '#cdd5e0',
          400: '#9aa6b8',
          500: '#697587',
          600: '#4b5666',
          700: '#364150',
          800: '#1f2733',
          900: '#131a24',
          950: '#0b0f17',
        },
        blue: {
          50:  '#eef4ff',
          100: '#dbe6ff',
          200: '#bcd1ff',
          300: '#8fb1ff',
          400: '#5b8bf8',
          500: '#3074ef',
          600: '#1f6feb',
          700: '#1857c4',
          800: '#18489b',
          900: '#173d7d',
        },
        green: {
          50:  '#e7f6ee',
          100: '#c8ecd8',
          200: '#94dab5',
          300: '#54c389',
          500: '#16a063',
          600: '#0f8a53',
          700: '#0c7044',
          800: '#0a5836',
        },
        red: {
          50:  '#fdecec',
          100: '#fbd5d6',
          200: '#f6abae',
          300: '#ef7e83',
          500: '#e0484e',
          600: '#cf353c',
          700: '#ad272e',
          800: '#8a2127',
        },
        amber: {
          50:  '#fdf4e3',
          100: '#fae6bf',
          200: '#f3cd80',
          500: '#d6961f',
          600: '#b97c12',
          700: '#92600d',
        },
        app: {
          bg:    'var(--app-bg)',
          surface: 'var(--surface)',
          'surface-2': 'var(--surface-2)',
          'surface-3': 'var(--surface-3)',
          'sidebar-bg': 'var(--sidebar-bg)',
        },
        semantic: {
          border:       'var(--border)',
          'border-strong': 'var(--border-strong)',
          'border-focus':  'var(--border-focus)',
          'text-strong':   'var(--text-strong)',
          text:          'var(--text)',
          'text-muted':  'var(--text-muted)',
          'text-faint':  'var(--text-faint)',
          primary:       'var(--primary)',
          'primary-hover': 'var(--primary-hover)',
          accent:        'var(--accent)',
          success:       'var(--success)',
          danger:        'var(--danger)',
          warning:       'var(--warning)',
        },
      },
      fontFamily: {
        sans:  ['Inter', 'system-ui', '-apple-system', 'sans-serif'],
        mono:  ['"JetBrains Mono"', 'ui-monospace', '"SF Mono"', 'Menlo', 'monospace'],
      },
      fontSize: {
        micro:  ['11px', { lineHeight: '1.4' }],
        xs:     ['12px', { lineHeight: '1.5' }],
        sm:     ['13px', { lineHeight: '1.5' }],
        base:   ['14px', { lineHeight: '1.55' }],
        md:     ['15px', { lineHeight: '1.55' }],
        lg:     ['17px', { lineHeight: '1.3' }],
        xl:     ['20px', { lineHeight: '1.25' }],
        '2xl':  ['24px', { lineHeight: '1.18' }],
        '3xl':  ['30px', { lineHeight: '1.12' }],
        '4xl':  ['40px', { lineHeight: '1.05' }],
        '5xl':  ['52px', { lineHeight: '1' }],
      },
      borderRadius: {
        xs:   '4px',
        sm:   '6px',
        md:   '8px',
        lg:   '10px',
        xl:   '14px',
        '2xl': '20px',
        full: '999px',
      },
      letterSpacing: {
        label:  '0.10em',
        tight:  '-0.012em',
        tighter: '-0.02em',
      },
      transitionTimingFunction: {
        ease:   'cubic-bezier(0.2, 0, 0, 1)',
        'ease-out': 'cubic-bezier(0.16, 1, 0.3, 1)',
      },
      transitionDuration: {
        fast: '120ms',
        DEFAULT: '180ms',
        slow: '320ms',
      },
      boxShadow: {
        xs: 'var(--shadow-xs)',
        sm: 'var(--shadow-sm)',
        md: 'var(--shadow-md)',
        lg: 'var(--shadow-lg)',
      },
    },
  },
  plugins: [],
};

export default config;
