'use client';
import {useEffect,useState} from 'react';
import {AppShell} from '@/components/shell/AppShell';
import {Card,CardBody,CardHeader} from '@/components/ui/Card';
import {Button} from '@/components/ui/Button';
import {Alert} from '@/components/ui/Alert';
import {Badge} from '@/components/ui/Badge';

type Registration={id:string;regime:string;registrationNumber:string;filingFrequency:string};
type Summary={id:string;regime:string;periodStart:string;periodEnd:string;status:string};
type Classification={lineId:string;treatment:string;reason:string;evidence:string};
type Detail={saved:Summary&{inputs:{classifications:Classification[];periodEvidence:string;reviewNote:string};filingConfirmation?:string};current:any;sourceChanged:boolean};
const money=(n:number)=>new Intl.NumberFormat('en-CA',{style:'currency',currency:'CAD'}).format(n/100);
const date=(value:string)=>value.slice(0,10);
export default function TaxWorkpapers(){
 const [registrations,setRegistrations]=useState<Registration[]>([]),[items,setItems]=useState<Summary[]>([]),[selected,setSelected]=useState<Detail|null>(null);
 const [registrationId,setRegistration]=useState(''),[start,setStart]=useState(''),[end,setEnd]=useState(''),[periodEvidence,setEvidence]=useState('Prepared from LedgerPro source documents and general ledger reconciliation.');
 const [classifications,setClassifications]=useState<Classification[]>([]),[confirmation,setConfirmation]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState<{kind:'danger'|'success'|'info';text:string}|null>(null);
 const load=async()=>{const r=await fetch('/api/tax/workpapers',{cache:'no-store'}),j=await r.json();if(!r.ok)throw new Error(j.error);setItems(j.data.workpapers);setRegistrations(j.data.registrations);if(!registrationId&&j.data.registrations[0])setRegistration(j.data.registrations[0].id);};
 useEffect(()=>{load().catch(e=>setMessage({kind:'danger',text:e.message}));},[]);
 const open=async(id:string)=>{setBusy(true);try{const r=await fetch(`/api/tax/workpapers/${id}`,{cache:'no-store'}),j=await r.json();if(!r.ok)throw new Error(j.error);setSelected(j.data);setClassifications(j.data.saved.inputs.classifications);setEvidence(j.data.saved.inputs.periodEvidence);setConfirmation(j.data.saved.filingConfirmation||'');}catch(e){setMessage({kind:'danger',text:(e as Error).message});}finally{setBusy(false);}};
 const create=async()=>{setBusy(true);setMessage(null);try{const r=await fetch('/api/tax/workpapers',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({registrationId,periodStart:start,periodEnd:end,inputs:{classifications:[],periodEvidence,reviewNote:''}})}),j=await r.json();if(!r.ok)throw new Error(j.error);await load();await open(j.data.id);}catch(e){setMessage({kind:'danger',text:(e as Error).message});}finally{setBusy(false);}};
 const act=async(action:string)=>{if(!selected)return;setBusy(true);setMessage(null);try{const r=await fetch(`/api/tax/workpapers/${selected.saved.id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,inputs:{classifications,periodEvidence,reviewNote:selected.saved.inputs.reviewNote||''},...(action==='record_filing'?{confirmation}:{})})}),j=await r.json();if(!r.ok)throw new Error(j.error);await load();await open(selected.saved.id);setMessage({kind:'success',text:action==='record_filing'?'External filing confirmation recorded.':'Workpaper updated.'});}catch(e){setMessage({kind:'danger',text:(e as Error).message});}finally{setBusy(false);}};
 const classify=(lineId:string,key:keyof Classification,value:string)=>setClassifications(old=>{const found=old.find(x=>x.lineId===lineId)??{lineId,treatment:'reconciliation_only',reason:'',evidence:''};return [...old.filter(x=>x.lineId!==lineId),{...found,[key]:value}]});
 const current=selected?.current;
 return <AppShell><div className="content-head"><div><h1 className="greet">Tax Workpapers</h1><p className="sub">Reconcile tax source documents to the ledger and record external filing evidence.</p></div></div>
 {message&&<Alert variant={message.kind} className="mb-4">{message.text}</Alert>}
 <Alert variant="info" title="Filing boundary" className="mb-4">LedgerPro prepares workpapers. It does not submit a return or payment to a tax authority. QST, PST, and RST exports are supporting schedules, not official provincial return forms.</Alert>
 <div className="grid lg:grid-cols-[360px_1fr] gap-4"><div className="space-y-4"><Card><CardHeader><h2 className="font-semibold">New period</h2></CardHeader><CardBody className="space-y-3"><label className="block text-sm">Registration<select value={registrationId} onChange={e=>setRegistration(e.target.value)} className="input w-full mt-1">{registrations.map(r=><option key={r.id} value={r.id}>{r.regime.toUpperCase()} • {r.registrationNumber}</option>)}</select></label><div className="grid grid-cols-2 gap-2"><label className="text-sm">Start<input type="date" value={start} onChange={e=>setStart(e.target.value)} className="input w-full mt-1"/></label><label className="text-sm">End<input type="date" value={end} onChange={e=>setEnd(e.target.value)} className="input w-full mt-1"/></label></div><label className="block text-sm">Period evidence<textarea value={periodEvidence} onChange={e=>setEvidence(e.target.value)} className="input w-full mt-1 min-h-20"/></label><Button onClick={create} disabled={busy||!registrationId||!start||!end}>Create workpaper</Button></CardBody></Card>
 <Card><CardHeader><h2 className="font-semibold">Periods</h2></CardHeader><CardBody className="space-y-2">{items.length===0?<p className="text-sm text-[var(--text-muted)]">No workpapers yet.</p>:items.map(w=><button key={w.id} onClick={()=>open(w.id)} className="w-full text-left border border-[var(--border)] rounded-lg p-3 hover:bg-[var(--surface-2)]"><div className="flex justify-between gap-2"><span className="font-semibold uppercase">{w.regime.replace('_','/')}</span><Badge variant={w.status==='filed_recorded'?'paid':w.status==='draft'?'draft':'pending'}>{w.status.replace('_',' ')}</Badge></div><p className="text-sm text-[var(--text-muted)] mt-1">{date(w.periodStart)} to {date(w.periodEnd)}</p></button>)}</CardBody></Card></div>
 <div>{!current?<Card><CardBody><p className="text-[var(--text-muted)]">Create or select a workpaper to review its return lines and reconciliation.</p></CardBody></Card>:<div className="space-y-4">{selected!.sourceChanged&&<Alert variant="warning" title="Source data changed">The ledger or tax snapshots changed after this version was saved. Save the draft again, or prepare a new amended period if filing was already recorded.</Alert>}{current.blockers.length>0&&<Alert variant="warning" title="Reconciliation blockers"><ul className="list-disc ml-5">{current.blockers.map((b:string)=><li key={b}>{b}</li>)}</ul></Alert>}
 <div className="grid grid-cols-3 gap-3"><Card><CardBody><div className="text-sm text-[var(--text-muted)]">Output tax</div><div className="text-xl font-semibold">{money(current.outputMinor)}</div></CardBody></Card><Card><CardBody><div className="text-sm text-[var(--text-muted)]">Recoverable tax</div><div className="text-xl font-semibold">{money(current.recoveryMinor)}</div></CardBody></Card><Card><CardBody><div className="text-sm text-[var(--text-muted)]">Net tax</div><div className="text-xl font-semibold">{money(current.netTaxMinor)}</div></CardBody></Card></div>
 {!current.scheduleOnly&&<Card><CardHeader><h2 className="font-semibold">GST/HST regular-method lines</h2></CardHeader><CardBody><div className="grid grid-cols-2 sm:grid-cols-4 gap-3">{Object.entries(current.lines).map(([line,amount])=><div key={line} className="border border-[var(--border)] rounded-lg p-3"><div className="text-xs text-[var(--text-muted)]">Line {line}</div><div className="font-semibold">{money(amount as number)}</div></div>)}</div></CardBody></Card>}
 <Card><CardHeader><h2 className="font-semibold">Control-account reconciliation</h2></CardHeader><CardBody><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b"><th className="text-left p-2">Role</th><th className="text-left p-2">Account</th><th className="text-right p-2">Opening</th><th className="text-right p-2">Movement</th><th className="text-right p-2">Closing</th></tr></thead><tbody>{current.balances.map((b:any)=><tr key={b.role} className="border-b"><td className="p-2">{b.role}</td><td className="p-2">{b.code}</td><td className="text-right p-2">{money(b.openingMinor)}</td><td className="text-right p-2">{money(b.movementMinor)}</td><td className="text-right p-2">{money(b.closingMinor)}</td></tr>)}</tbody></table></div></CardBody></Card>
 {current.unclassified.length>0&&<Card><CardHeader><h2 className="font-semibold">Manual and legacy classifications</h2></CardHeader><CardBody className="space-y-3">{current.unclassified.map((l:any)=>{const c=classifications.find(x=>x.lineId===l.id);return <div key={l.id} className="border border-[var(--border)] rounded-lg p-3 grid md:grid-cols-3 gap-2"><div><div className="font-medium">{l.date} • {l.code}</div><div className="text-sm text-[var(--text-muted)]">Dr {money(l.debitMinor)} / Cr {money(l.creditMinor)}<br/>{l.description}</div></div><select value={c?.treatment||''} onChange={e=>classify(l.id,'treatment',e.target.value)} className="input"><option value="">Choose treatment</option><option value="line101">Line 101</option><option value="line103">Line 103</option><option value="line104">Line 104</option><option value="line106">Line 106</option><option value="line107">Line 107</option><option value="line110">Line 110 instalment</option><option value="reconciliation_only">Reconciliation only</option></select><div className="space-y-2"><input className="input w-full" placeholder="Reason" value={c?.reason||''} onChange={e=>classify(l.id,'reason',e.target.value)}/><input className="input w-full" placeholder="Evidence reference" value={c?.evidence||''} onChange={e=>classify(l.id,'evidence',e.target.value)}/></div></div>})}</CardBody></Card>}
 <Card><CardBody className="flex flex-wrap gap-2 items-end">{selected!.saved.status==='draft'&&<><Button variant="secondary" onClick={()=>act('save')} disabled={busy}>Save draft</Button><Button onClick={()=>act('prepare')} disabled={busy}>Mark prepared</Button></>}{selected!.saved.status==='prepared'&&<><Button onClick={()=>act('review')} disabled={busy||selected!.sourceChanged}>Approve review</Button><Button variant="secondary" onClick={()=>act('reopen')} disabled={busy}>Reopen draft</Button></>}{selected!.saved.status==='reviewed'&&<><label className="text-sm flex-1 min-w-64">External filing confirmation<input className="input w-full mt-1" value={confirmation} onChange={e=>setConfirmation(e.target.value)} placeholder="CRA or provincial confirmation number"/></label><Button onClick={()=>act('record_filing')} disabled={busy||!confirmation.trim()||selected!.sourceChanged}>Record filing</Button><Button variant="secondary" onClick={()=>act('reopen')} disabled={busy}>Reopen draft</Button></>}<a href={`/api/tax/workpapers/${selected!.saved.id}/export`} className="h-[var(--control-h)] px-4 rounded-md border border-[var(--border-strong)] inline-flex items-center font-semibold text-sm">Download CSV</a></CardBody></Card></div>}</div></div></AppShell>;
}
